In [1]:
%reload_ext autoreload
%autoreload 2

# Imports

In [2]:
from kret_notebook import *  # NOTE import first
from kret_lgbm._core.lgbm_nb_imports import *
from kret_lightning._core.lightning_nb_imports import *
from kret_matplotlib._core.mpl_nb_imports import *
from kret_np_pd._core.np_pd_nb_imports import *
from kret_optuna._core.optuna_nb_imports import *
from kret_polars._core.polars_nb_imports import *
from kret_rosetta._core.rosetta_nb_imports import *
from kret_sklearn._core.sklearn_nb_imports import *
from kret_torch_utils._core.torch_nb_imports import *
from kret_tqdm._core.tqdm_nb_imports import *
from kret_type_hints._core.types_nb_imports import *
from kret_utils._core.utils_nb_imports import *

# from kret_wandb._core.wandb_nb_imports import *  # NOTE this is slow to import

Loaded environment variables from /home/Akseldkw/coding/nba/NBA-Timeout-Impact/.env
[kret_lgbm._core.lgbm_nb_imports] Imported kret_lgbm._core.lgbm_nb_imports in 1.7195 seconds
[kret_lightning._core.lightning_nb_imports] Imported kret_lightning._core.lightning_nb_imports in 4.8798 seconds
[kret_matplotlib._core.mpl_nb_imports] Imported kret_matplotlib._core.mpl_nb_imports in 0.2538 seconds
[kret_np_pd._core.np_pd_nb_imports] Imported kret_np_pd._core.np_pd_nb_imports in 0.0007 seconds
[kret_optuna._core.optuna_nb_imports] Imported kret_optuna._core.optuna_nb_imports in 0.0006 seconds
[kret_polars._core.polars_nb_imports] Imported kret_polars._core.polars_nb_imports in 0.3428 seconds
[kret_rosetta._core.rosetta_nb_imports] Imported kret_rosetta._core.rosetta_nb_imports in 0.0000 seconds
[kret_sklearn._core.sklearn_nb_imports] Imported kret_sklearn._core.sklearn_nb_imports in 0.0301 seconds
[kret_torch_utils._core.torch_nb_imports] Imported kret_torch_utils._core.torch_nb_imports in 0.1489 seconds
[kret_tqdm._core.tqdm_nb_imports] Imported kret_tqdm._core.tqdm_nb_imports in 0.0001 seconds
[kret_type_hints._core.types_nb_imports] Imported kret_type_hints._core.types_nb_imports in 0.0005 seconds
[kret_utils._core.utils_nb_imports] Imported kret_utils._core.utils_nb_imports in 0.0004 seconds

In [3]:
from nba_timeout_impact.nb_imports import *

# Load Data

In [4]:
cdnnba = NBADataLoader.load_seasons(data_type="cdnnba", playoffs=False)

Loading data_type='cdnnba', seasons=[2020, 2021, 2022, 2023, 2024, 2025], playoffs=False...

/home/Akseldkw/coding/nba/NBA-Timeout-Impact/nba_timeout_impact/data_pipes/load_data_utils.py:128: DtypeWarning: Columns (0: isTargetScoreLastPeriod, 1: shortFormattedClock) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(f, **read_csv_kwargs)

In [5]:
cdnnba_playoff = NBADataLoader.load_seasons(data_type="cdnnba", playoffs=True)

Loading data_type='cdnnba', seasons=[2020, 2021, 2022, 2023, 2024], playoffs=True...

In [6]:
UKS_NP_PD.dtt([cdnnba, cdnnba_playoff], show_dims=True, num_cols=1)

# Implementation

# Sandbox