In [1]:
%reload_ext autoreload
%autoreload 2

# Imports

In [2]:
from kret_notebook import *  # NOTE import first
from kret_lgbm._core.lgbm_nb_imports import *
from kret_lightning._core.lightning_nb_imports import *
from kret_matplotlib._core.mpl_nb_imports import *
from kret_np_pd._core.np_pd_nb_imports import *
from kret_optuna._core.optuna_nb_imports import *
from kret_polars._core.polars_nb_imports import *
from kret_rosetta._core.rosetta_nb_imports import *
from kret_sklearn._core.sklearn_nb_imports import *
from kret_torch_utils._core.torch_nb_imports import *
from kret_tqdm._core.tqdm_nb_imports import *
from kret_type_hints._core.types_nb_imports import *
from kret_utils._core.utils_nb_imports import *

# from kret_wandb._core.wandb_nb_imports import *  # NOTE this is slow to import

Loaded environment variables from /Users/Akseldkw/coding/Columbia/NBA-Timeout-Impact/.env
[kret_lgbm._core.lgbm_nb_imports] Imported kret_lgbm._core.lgbm_nb_imports in 2.0715 seconds
[kret_lightning._core.lightning_nb_imports] Imported kret_lightning._core.lightning_nb_imports in 4.2922 seconds
[kret_matplotlib._core.mpl_nb_imports] Imported kret_matplotlib._core.mpl_nb_imports in 0.3133 seconds
[kret_np_pd._core.np_pd_nb_imports] Imported kret_np_pd._core.np_pd_nb_imports in 0.0006 seconds
[kret_optuna._core.optuna_nb_imports] Imported kret_optuna._core.optuna_nb_imports in 0.0008 seconds
[kret_polars._core.polars_nb_imports] Imported kret_polars._core.polars_nb_imports in 0.0963 seconds
[kret_rosetta._core.rosetta_nb_imports] Imported kret_rosetta._core.rosetta_nb_imports in 0.0000 seconds
[kret_sklearn._core.sklearn_nb_imports] Imported kret_sklearn._core.sklearn_nb_imports in 0.1984 seconds
[kret_torch_utils._core.torch_nb_imports] Imported kret_torch_utils._core.torch_nb_imports in 0.3956 seconds
[kret_tqdm._core.tqdm_nb_imports] Imported kret_tqdm._core.tqdm_nb_imports in 0.0002 seconds
[kret_type_hints._core.types_nb_imports] Imported kret_type_hints._core.types_nb_imports in 0.0006 seconds
[kret_utils._core.utils_nb_imports] Imported kret_utils._core.utils_nb_imports in 0.0009 seconds

In [ ]:
from nba_timeout_impact.data_utils import *

# Load Data

In [ ]:
ret = available_seasons(data_type="nbastats")

In [7]:
ret

[1996,
 1997,
 1998,
 1999,
 2000,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 2023,
 2024]

In [14]:
nba_stats = load_seasons(data_type="nbastats", playoffs=True)

In [18]:
UKS_NP_PD.dtt([nba_stats], show_dims=True)

In [19]:
nba_statsv3 = load_seasons(data_type="nbastatsv3", playoffs=True)

In [20]:
UKS_NP_PD.dtt([nba_statsv3], show_dims=True)

In [ ]:
cdnnba = load_seasons(data_type="cdnnba", playoffs=True)

FileNotFoundError: Dataset not found: /Users/Akseldkw/coding/Columbia/nba_data/datasets/cdnnba_po_2018.tar.xz
Available files: [PosixPath('/Users/Akseldkw/coding/Columbia/nba_data/datasets/cdnnba_2020.tar.xz'), PosixPath('/Users/Akseldkw/coding/Columbia/nba_data/datasets/cdnnba_2021.tar.xz'), PosixPath('/Users/Akseldkw/coding/Columbia/nba_data/datasets/cdnnba_2022.tar.xz'), PosixPath('/Users/Akseldkw/coding/Columbia/nba_data/datasets/cdnnba_2023.tar.xz'), PosixPath('/Users/Akseldkw/coding/Columbia/nba_data/datasets/cdnnba_2024.tar.xz'), PosixPath('/Users/Akseldkw/coding/Columbia/nba_data/datasets/cdnnba_2025.tar.xz'), PosixPath('/Users/Akseldkw/coding/Columbia/nba_data/datasets/cdnnba_po_2020.tar.xz'), PosixPath('/Users/Akseldkw/coding/Columbia/nba_data/datasets/cdnnba_po_2021.tar.xz'), PosixPath('/Users/Akseldkw/coding/Columbia/nba_data/datasets/cdnnba_po_2022.tar.xz'), PosixPath('/Users/Akseldkw/coding/Columbia/nba_data/datasets/cdnnba_po_2023.tar.xz'), PosixPath('/Users/Akseldkw/coding/Columbia/nba_data/datasets/cdnnba_po_2024.tar.xz')]

In [25]:
UKS_NP_PD.dtt([cdnnba], show_dims=True)

NameError: name 'cdnnba' is not defined

In [21]:
data_nba = load_seasons(data_type="datanba", playoffs=True)

/Users/Akseldkw/coding/Columbia/NBA-Timeout-Impact/nba_timeout_impact/data_utils.py:106: DtypeWarning: Columns (0: wallclk) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(f)

In [22]:
UKS_NP_PD.dtt([data_nba], show_dims=True)

# Implementation

# Sandbox