In [6]:
%reload_ext autoreload
%autoreload 2

# Imports

In [7]:
from kret_notebook import *  # NOTE import first
from kret_lgbm._core.lgbm_nb_imports import *
from kret_lightning._core.lightning_nb_imports import *
from kret_matplotlib._core.mpl_nb_imports import *
from kret_np_pd._core.np_pd_nb_imports import *
from kret_optuna._core.optuna_nb_imports import *
from kret_polars._core.polars_nb_imports import *
from kret_rosetta._core.rosetta_nb_imports import *
from kret_sklearn._core.sklearn_nb_imports import *
from kret_torch_utils._core.torch_nb_imports import *
from kret_tqdm._core.tqdm_nb_imports import *
from kret_type_hints._core.types_nb_imports import *
from kret_utils._core.utils_nb_imports import *

# from kret_wandb._core.wandb_nb_imports import *  # NOTE this is slow to import

In [8]:
from nba_timeout_impact.load_data_utils import NBADataLoader
from nba_timeout_impact.clean_pipeline import NBAStatsV3CleanPipeline
from nba_timeout_impact.constants import NBAConstants
from nba_timeout_impact.nba_dataset import NBADataset

In [9]:
UKS_CONSTANTS.DATA_DIR

PosixPath('/Users/Akseldkw/coding/data_kretsinger')

In [10]:
NBA_DATA_DIR = UKS_CONSTANTS.DATA_DIR / "NBA"
os.makedirs(NBA_DATA_DIR, exist_ok=True)

# Load Data

In [11]:
raise ValueError("Skip Loading Data, Jump to Pipeline section")

ValueError: Skip Loading Data, Jump to Pipeline section

In [ ]:
# nba_statsv3 = NBADataLoader.load_seasons(data_type="nbastatsv3", playoffs=False, seasons=None)
nba_statsv3 = pd.read_parquet(NBA_DATA_DIR / "nba_statsv3_regular_season.parquet")
nba_statsv3["IsPlayoff"] = False

In [ ]:
# nba_statsv3_po = NBADataLoader.load_seasons(data_type="nbastatsv3", playoffs=True, seasons=None)
nba_statsv3_po = pd.read_parquet(NBA_DATA_DIR / "nba_statsv3_playoffs.parquet")
nba_statsv3_po["IsPlayoff"] = True

In [ ]:
nba_statsv3_all = pd.concat([nba_statsv3, nba_statsv3_po], ignore_index=True)

In [ ]:
nba_statsv3_all.to_parquet(NBA_DATA_DIR / "nba_statsv3.parquet")

In [ ]:
# early = NBADataLoader.load_game_dates_from_api(seasons=[1996, 1997, 1998, 1999])
# early_po = NBADataLoader.load_game_dates_from_api(seasons=[1996, 1997, 1998, 1999], playoffs=True)
# dates_nba = NBADataLoader.load_game_dates()
# dates_nba_po = NBADataLoader.load_game_dates(playoffs=True)

nba_game_dates = pd.read_parquet(NBA_DATA_DIR / "nba_game_dates.parquet")
dates_all = nba_game_dates

In [ ]:
game_date_map = dates_all.set_index("GAME_ID")["game_date"]
nba_statsv3["game_date"] = nba_statsv3["gameId"].map(game_date_map)

# Implementation

In [ ]:
# nba_statsv3.to_parquet(NBA_DATA_DIR / "nba_statsv3_regular_season.parquet")

In [ ]:
# nba_statsv3_po.to_parquet(NBA_DATA_DIR / "nba_statsv3_playoffs.parquet")

In [ ]:
# reload = pd.read_parquet(NBA_DATA_DIR / "nba_statsv3_regular_season.parquet")

# Pipeline

In [12]:
from nba_timeout_impact.clean_pipeline import SortByDate, CategoricalConversion

In [21]:
pipeline = NBAStatsV3CleanPipeline(NBA_DATA_DIR)
clean = pipeline.run()

In [22]:
UKS_NP_PD.dtt([clean], how="tail", show_dims=True, n=20)

In [23]:
pipeline.save(clean, NBA_DATA_DIR / "nba_statsv3_clean.parquet")

Saved 18,049,803 rows x 30 cols -> /Users/Akseldkw/coding/data_kretsinger/NBA/nba_statsv3_clean.parquet

PosixPath('/Users/Akseldkw/coding/data_kretsinger/NBA/nba_statsv3_clean.parquet')

In [20]:
clean.scoreAway.isna().sum()

np.int64(0)

In [ ]:
UKS_NP_PD.count_unique(clean)

,game_date_ffill,gameId,actionId,actionType,subType,scoreHome,scoreAway,pointsTotal,period,teamTricode,shotResult,isFieldGoal,location,description,shotValue,IsPlayoff,seconds_remaining,seconds_elapsed,game_date,playerNameI,actionNumber,clock,teamId,personId,playerName,xLegacy,yLegacy,shotDistance,videoAvailable
,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64
0,5869,37514,745,14,185,173,173,342,8,36,2,2,2,3784108,3,2,1261,1801,5869,2597,998,1261,31,3638,1887,539,929,93,2

In [ ]:
type(pd.to_datetime(clean.game_date))

pandas.Series

# Sanbox

In [ ]:
stacked_raw = pd.read_parquet(NBA_DATA_DIR / "nba_statsv3.parquet")

In [ ]:
f_gameid = stacked_raw.gameId == 29600001

In [ ]:
scoreAwayFix = stacked_raw.groupby("gameId")["scoreAway"].cummax()

In [ ]:
UKS_NP_PD.dtt([stacked_raw, scoreAwayFix], filter=f_gameid, how="head")