In [1]:
%reload_ext autoreload
%autoreload 2

# Imports

In [2]:
from kret_notebook import *  # NOTE import first
from kret_lgbm._core.lgbm_nb_imports import *
from kret_lightning._core.lightning_nb_imports import *
from kret_matplotlib._core.mpl_nb_imports import *
from kret_np_pd._core.np_pd_nb_imports import *
from kret_optuna._core.optuna_nb_imports import *
from kret_polars._core.polars_nb_imports import *
from kret_rosetta._core.rosetta_nb_imports import *
from kret_sklearn._core.sklearn_nb_imports import *
from kret_torch_utils._core.torch_nb_imports import *
from kret_tqdm._core.tqdm_nb_imports import *
from kret_type_hints._core.types_nb_imports import *
from kret_utils._core.utils_nb_imports import *

# from kret_wandb._core.wandb_nb_imports import *  # NOTE this is slow to import

Loaded environment variables from /Users/Akseldkw/coding/Columbia/NBA-Timeout-Impact/.env
[kret_lgbm._core.lgbm_nb_imports] Imported kret_lgbm._core.lgbm_nb_imports in 2.0687 seconds
[kret_lightning._core.lightning_nb_imports] Imported kret_lightning._core.lightning_nb_imports in 4.3732 seconds
[kret_matplotlib._core.mpl_nb_imports] Imported kret_matplotlib._core.mpl_nb_imports in 0.0297 seconds
[kret_np_pd._core.np_pd_nb_imports] Imported kret_np_pd._core.np_pd_nb_imports in 0.0005 seconds
[kret_optuna._core.optuna_nb_imports] Imported kret_optuna._core.optuna_nb_imports in 0.0007 seconds
[kret_polars._core.polars_nb_imports] Imported kret_polars._core.polars_nb_imports in 0.1154 seconds
[kret_rosetta._core.rosetta_nb_imports] Imported kret_rosetta._core.rosetta_nb_imports in 0.0000 seconds
[kret_sklearn._core.sklearn_nb_imports] Imported kret_sklearn._core.sklearn_nb_imports in 0.1810 seconds
[kret_torch_utils._core.torch_nb_imports] Imported kret_torch_utils._core.torch_nb_imports in 0.4072 seconds
[kret_tqdm._core.tqdm_nb_imports] Imported kret_tqdm._core.tqdm_nb_imports in 0.0002 seconds
[kret_type_hints._core.types_nb_imports] Imported kret_type_hints._core.types_nb_imports in 0.0007 seconds
[kret_utils._core.utils_nb_imports] Imported kret_utils._core.utils_nb_imports in 0.0011 seconds

In [3]:
from nba_timeout_impact.load_data_utils import NBADataLoader
from nba_timeout_impact.clean_pipeline import NBAStatsV3CleanPipeline
from nba_timeout_impact.constants import NBAConstants
from nba_timeout_impact.nba_dataset import NBADataset, NBAMemoDF, NBADatasetInput_TypedDict

# Load Data

In [4]:
NBA_DATA_DIR = NBAConstants.NBA_DATA_DIR

In [5]:
nba = pd.read_parquet(NBA_DATA_DIR / "nba_statsv3_clean.parquet")

In [6]:
UKS_NP_PD.dtt([nba], how="head", filter=nba.IsPlayoff)

,actionNumber,clock,period,teamId,teamTricode,personId,playerName,playerNameI,xLegacy,yLegacy,shotDistance,shotResult,isFieldGoal,scoreHome,scoreAway,pointsTotal,location,description,actionType,subType,videoAvailable,actionId,gameId,shotValue,IsPlayoff,seconds_remaining,seconds_elapsed,game_date,game_date_ffill
,int64,str,int64,int64,category,int64,category,category,int64,int64,int64,category,int64,float64,float64,int64,category,str,category,category,int64,int64,int64,float64,bool,float64,float64,datetime64[ms],datetime64[ms]
562501,0,PT12M00.00S,1,0,NaN,0,NaN,NaN,0,0,0,NaN,0,0.000,0.000,0,NaN,Start of 1st Period (11:12 PM EST),period,start,0,1,49600001,NaN,True,720.000,0.000,1997-04-24,1997-04-24
562502,1,PT12M00.00S,1,1610612752,NYK,121,Ewing,P. Ewing,0,0,0,NaN,0,NaN,NaN,0,h,Jump Ball Ewing vs. Divac: Tip to Childs,Jump Ball,NaN,0,2,49600001,NaN,True,720.000,0.000,1997-04-24,1997-04-24
562503,2,PT11M47.00S,1,1610612752,NYK,275,Houston,A. Houston,-107,36,11,Made,1,2.000,0.000,2,h,Houston 11' Jump Shot (2 PTS) (Childs 1 AST),Made Shot,Jump Shot,0,3,49600001,NaN,True,707.000,13.000,1997-04-24,1997-04-24
562504,3,PT11M31.00S,1,1610612766,CHH,779,Rice,G. Rice,0,0,0,NaN,0,NaN,NaN,0,v,Rice Bad Pass Turnover (P1.T1),Turnover,Bad Pass,0,4,49600001,NaN,True,691.000,29.000,1997-04-24,1997-04-24
562505,3,PT11M31.00S,1,1610612752,NYK,275,Houston,A. Houston,0,0,0,NaN,0,NaN,NaN,0,h,Houston STEAL (1 STL),NaN,NaN,0,5,49600001,NaN,True,691.000,29.000,1997-04-24,1997-04-24

In [7]:
nba = NBADataset.load_from_parquet()

# Implementation

In [19]:
nba_memo = NBAMemoDF({"data": nba})

In [ ]:
nba_memo.f_timeout.mean()

np.float64(0.02632555047830716)

In [ ]:
UKS_NP_PD.dtt(nba_memo.data, filter=nba_memo.f_timeout)

,actionNumber,clock,period,teamId,teamTricode,personId,playerName,playerNameI,xLegacy,yLegacy,shotDistance,shotResult,isFieldGoal,scoreHome,scoreAway,pointsTotal,location,description,actionType,subType,videoAvailable,actionId,gameId,shotValue,IsPlayoff,seconds_remaining,seconds_elapsed,game_date,game_date_ffill
,int64,str,int64,int64,category,int64,category,category,int64,int64,int64,category,int64,float64,float64,int64,category,str,category,category,int64,int64,int64,float64,bool,float64,float64,datetime64[ms],datetime64[ms]
1584778,459,PT06M08.00S,4,0,NaN,1610612744,NaN,NaN,0,0,0,NaN,0,NaN,NaN,0,v,Warriors Timeout: Regular (Reg.5 Short 1),Timeout,Regular,0,450,29900007,NaN,False,368.000,352.000,1999-11-02,1999-11-02
3566087,195,PT06M55.00S,2,0,NaN,1610612765,NaN,NaN,0,0,0,NaN,0,0.000,0.000,0,v,Pistons Timeout: Regular (Reg.2 Short 0),Timeout,Regular,0,174,20200359,NaN,False,415.000,305.000,2002-12-18,2002-12-18
4730796,464,PT03M04.00S,4,0,NaN,1610612737,NaN,NaN,0,0,0,NaN,0,0.000,0.000,0,h,HAWKS Timeout: Regular (Full 5 Short 2),Timeout,Regular,0,457,20400265,NaN,False,184.000,536.000,2004-12-08,2004-12-08
6154560,130,PT08M53.00S,2,0,NaN,0,NaN,NaN,0,0,0,NaN,0,0.000,0.000,0,NaN,Timeout: Official,Timeout,Official,0,133,20600622,NaN,False,533.000,187.000,2007-01-24,2007-01-24
14072238,113,PT03M33.00S,1,0,NaN,1610612737,NaN,NaN,0,0,0,NaN,0,NaN,NaN,0,v,Hawks Timeout: Regular (Reg.1 Short 0),Timeout,Regular,0,86,21900336,NaN,False,213.000,507.000,2019-12-08,2019-12-08

In [25]:
nba_memo.actionType[nba_memo.f_timeout].value_counts()

actionType
Timeout           475171
Ejection               0
Foul                   0
Free Throw             0
Heave                  0
Instant Replay         0
Jump Ball              0
Made Shot              0
Missed Shot            0
Rebound                0
Substitution           0
Turnover               0
Violation              0
period                 0
Name: count, dtype: int64

In [ ]:
subtype_counts = nba_memo.subType[nba_memo.f_timeout].value_counts()
dtt([subtype_counts], n=10, how="head")

,count
,int64
subType,
Regular,374204
Short,56098
Official,40318
Official TV,2795
Coach Challenge,1653
,102
Advance,1
10 Second Violaton,0
3 Second Violation,0
5 Second Inbound Turnover,0

# Sandbox